### ISSUE TITLE
Quotes are stripped for args passed through to package managers

### ISSUE THREAD

**Issue by joelwass** [flossbank/cli#73]
From https://twitter.com/sebsilbermann/status/1286616779033387008: 

Quote strings seem to be stripped e.g. in `yarn test --grep "Tooltip /"` the quotes get stripped resulting in `mocha --grep Tooltip /` which is not the same

Looks like this can be repro'd with any package manager args that include a space

**Comment by eps1lon** [comment]
Fixed on 
```bash
$ flossbank --version
0.0.35
```

**Comment by stripedpajamas** [comment]
Yay! Thanks for confirming @eps1lon
